spring:
  cloud:
    gcp:
      datastore:
        # fill a project-id in GCP
        project-id: excellent-tide-369221
        # fill credentials of a service account
        credentials:
          location: classpath:excellent-tide-369221-c2c3088ed4f4.json
